[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
py_version = 310
skip = [".gitignore", ".dockerignore"]
use_parentheses = true

[tool.black]
line-length = 88
target-version = ['py310']

[tool.pycln]
all = true

[tool.mypy]

# Allows variables to be redefined with an arbitrary type,
# as long as the redefinition is in the same block and
# nesting level as the original definition.
allow_redefinition = true

# Suppresses error messages about imports that cannot be resolved.
ignore_missing_imports = true

# If a type stub package is missing from the environment but available on typeshed, automatically
# install it. Note that without `--non-interactive` this will prompt the user.
install_types = true

# Enables PEP 420 style namespace packages.
namespace_packages = true

# Shows error codes in error messages.
show_error_codes = true
