[tool.jupytext]
formats = "ipynb,py:percent"

[tool.black-jupyter]
target-version = ['py310']

[tool.isort]
float_to_top = true
profile = "black"
py_version = 310
skip = [".gitignore", ".dockerignore"]
treat_comments_as_code = ["# %%"]

[tool.pycln]
all = true
